<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo $this->headTitle(); ?>
<?php echo $this->headMeta(); ?> 
<meta name="distribution" content="Global"/>
<meta name="robots" content="index,follow" />
<meta name="alexa" content="100"/>
<meta name="Abstract" content=""/>
<meta name="web_author" content="HoaiTN"/>
<meta name="copyright" content="HoaiTN"/>
<meta name="google-site-verification" content="" />
<base href="http://<?php echo $_SERVER['HTTP_HOST'].$this->baseUrl()?>/" />
	<link href="css/style.css" rel="stylesheet" type="text/css" />
	<link href="css/layout.css" rel="stylesheet" type="text/css" />
	<script src="js/maxheight.js" type="text/javascript"></script>
	<script src="js/jquery.uniform.min.js" type="text/javascript"></script>
	<script src="js/jquery-1.6.1.min.js" type="text/javascript"></script>
	<script src="js/default.js" type="text/javascript"></script>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-27224693-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>		
<!--[if lte IE 7]>
     <link rel="stylesheet" type="text/css" href="css/ie.css" media="screen" />
<![endif]-->
 <link rel="canonical" href="http://<?php echo $_SERVER['HTTP_HOST'].$this->baseUrl().$this->url()?>" /> 
</head>

<body id="index" onload="new ElementMaxHeight();">
	<div id="header_tall">
		<div id="main">
			<!--header -->
			<?php echo $this->partial("menu/head_menu.phtml")?>
			<!--header end-->
			<?php echo $this->layout()->content;?>
			<!--footer -->
			<?php echo $this->partial('menu/footer.phtml');?>
			<!--footer end-->
		</div>
	</div>
</body>
</html>
