<div class="hastable">
<h1>Management setions</h1>
<div id="qlqg" style="padding-bottom: 10px;">
<a class="btn_no_text btn ui-state-default ui-corner-all tooltip" href="<?php echo $this->url(array('controller'=>'sections','action'=>'create'))?>"><button>Add sections</button></a>
<?php echo $this->Pagination($this->Pager,$this->url().'?page={%page}')?>
</div>
<table cellspacing="0" cellpadding="0" width="100%" class="tbl_list">
		<thead>
			<th>Name</th>
			<th>Edit</th>
			<th>Delete</th>
		</thead>
		<?php foreach($this->Setions as $Group):?>
		<tr class="<?php ++$i; echo($i%2)?'first':'second'?>">
			<td><?php echo $Group->name?></td>	
			<td align="center" width="40px;"><a href="<?php echo $this->url(array('controller'=>'sections','action'=>'edit','id'=>$Group->id))?>"><img src="<?php echo $this->baseUrl('images/image_edit.png');?>" width="24px;"/></a></td>
			<td align="center" width="40px;"><a href="<?php echo $this->url(array('controller'=>'sections','action'=>'delete','id'=>$Group->id))?>"><img src="<?php echo $this->baseUrl('images/Delete.png');?>" width="24px;"/></a></td>
		</tr>
		<?php endforeach;?>
</table>