<div class="block-controls">	
	<ul class="controls-tabs js-tabs same-height with-children-tip">
		<li class="current" title="Basic info"><a title="" href="#tabs-1"><img height="24" width="24" src="<?php echo $this->baseUrl('images/icons/web-app/24/Profile.png');?>"></a></li>
	</ul>	
</div>
<?php if($this->error):?>
<div class="block-content no-title dark-bg">
    <p class="mini-infos">          
          <?php foreach($this->error as $error){echo '- '.$error.'<br/>';}?>
    </p>
</div>    
<?php endif;?>
<h1>Create a video</h1>
<form action="" method="post" enctype="multipart/form-data">
<div id="tabs-1" class="hastable">
<table>
	<tr>
		<td width="130"><span style="color:#CC0000;">*</span>Name video</td>
		<td><?php echo $this->formText('name',$_REQUEST['name'],array('size'=>60 ))?></td>
	</tr>	
	<tr>
		<td width="130"><span style="color:#CC0000;">*</span>Video link</td>
		<td>You must be enter embed link<br/><?php echo $this->formTextarea('link',$_REQUEST['link'],array('rows'=>5))?></td>
	</tr>
	<tr>
		<td width="130">Category news</td>
		<td><?php $group = NewGroup::getOption(array("--- Select option ---")); echo $this->formSelect('group_id',$_REQUEST['group_id'],null,$group)?> </td>
	</tr>
</table>
</div>
<button type="submit">Save</button>
&nbsp;
<button type="button" onclick="javascript:history.back()">Cancel</button>
</form>
</div>
