<div id="google_translate_element"></div><script>
function googleTranslateElementInit() {
  new google.translate.TranslateElement({
    pageLanguage: 'vi',
    includedLanguages: 'en,vi,ko',
    multilanguagePage: true,
    gaTrack: true,
    gaId: 'UA-27224693-1',
    layout: google.translate.TranslateElement.InlineLayout.SIMPLE
  }, 'google_translate_element');
}
</script><script src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
<!--<div style="border:0px solid #ccc;padding:10px 0px 3px 0px;text-align:center;background-color:none;min-width:235px; margin: 5px 0 5px 0;">-->

<!--GOOGLE TRANSLATE MINI FLAGS-->
<!--<div align="center" style="width:auto;">-->

<!-- Add Vietnames to English -->

<!--<a target="_blank" rel="nofollow" onclick="window.open('http://www.google.com/translate?u='+encodeURIComponent(location.href)+'&langpair=vi%7Cen&hl=vi&ie=UTF8'); return false;" title="Vietnames to English"><img border="0" style="cursor:pointer; cursor:hand;" width="25" alt="Vietnamese to English" src="images/language/en.png" height="19" title="translate to English"/></a>-->

<!-- END Vietnames to English -->
<!-- Add English to Vietnames -->

<!--<a target="_blank" rel="nofollow" onclick="window.open('http://www.google.com/translate?u='+encodeURIComponent(location.href)+'&langpair=en%7Cvi&hl=en&ie=UTF8'); return false;" title="Vietnames to English"><img border="0" style="cursor:pointer; cursor:hand;" width="25" alt="Vietnamese to English" src="images/language/vn.png" height="19" title="translate to Vietnamese"/></a>-->

<!-- END English to Vietnames -->


<!--</div>-->

<!--<small>↑ <a href="http://www.madtomatoe.com/google-translate-mini-flags-widget/" target="_blank">Google Translation</a> </small><br/>-->

<!--</div>-->
<!--<table width="320">-->
<!--	<tr>-->
<!--		<td>&nbsp;</td>-->
<!--		<form action="http://www.google.com/translate" target="_blank">-->
<!--		<td width="40"><script language="JavaScript">     document.write ("<input name=u value="+location.href+" type=hidden>")  //   </script>-->
<!--		<noscript><input name="u" value="http://labnol.blogspot.com"-->
<!--			type="hidden" /></noscript>-->
<!--		<input name="hl" value="vi" type="hidden">-->
<!--		 <input name="ie"-->
<!--			value="UTF8" type="hidden"> <input name="langpair" value=""-->
<!--			type="hidden"> <input name="langpair" value="vn|en"-->
<!--			title="Fran&#231;ais/French"-->
<!--			src="http://photos1.blogger.com/img/43/1633/320/13539949_e76af75976.jpg"-->
<!--			onclick="this.form.langpair.value=this.value" height="20"-->
<!--			type="image" width="30"></td>-->
<!--		<td width="40"><input name="langpair" value="en|de"-->
<!--			title="Deutsch/German"-->
<!--			src="http://photos1.blogger.com/img/43/1633/320/13539933_041ca1eda2.jpg"-->
<!--			onclick="this.form.langpair.value=this.value" height="20"-->
<!--			type="image" width="30"></td>-->
<!--		<td width="40"><input name="langpair" value="en|it"-->
<!--			title="Italiano/Italian"-->
<!--			src="http://photos1.blogger.com/img/43/1633/320/13539953_0384ccecf9.jpg"-->
<!--			onclick="this.form.langpair.value=this.value" height="20"-->
<!--			type="image" width="30"></td>-->
<!--		<td width="40"><input name="langpair" value="en|pt"-->
<!--			title="Portugu&#234;s/Portuguese"-->
<!--			src="http://photos1.blogger.com/img/43/1633/320/13539966_0d09b410b5.jpg"-->
<!--			onclick="this.form.langpair.value=this.value" height="20"-->
<!--			type="image" width="30"></td>-->
<!--		<td width="40"><input name="langpair" value="en|es"-->
<!--			title="Espa&#241;ol/Spanish"-->
<!--			src="http://photos1.blogger.com/img/43/1633/320/13539946_2fabed0dbf.jpg"-->
<!--			onclick="this.form.langpair.value=this.value" height="20"-->
<!--			type="image" width="30"></td>-->
<!--		<td width="40"><input name="langpair" value="en|ja"-->
<!--			title="&#26085;&#26412;&#35486;/Japanese"-->
<!--			src="http://photos1.blogger.com/img/43/1633/320/13539955_925e6683c8.jpg"-->
<!--			onclick="this.form.langpair.value=this.value" height="20"-->
<!--			type="image" width="30"></td>-->
<!--		<td width="40"><input name="langpair" value="en|ko"-->
<!--			title="&#54620;&#44397;&#50612;/Korean"-->
<!--			src="http://photos1.blogger.com/img/43/1633/320/13539958_3c3b482c95.jpg"-->
<!--			onclick="this.form.langpair.value=this.value" height="20"-->
<!--			type="image" width="30"></td>-->
<!--		<td width="40"><input name="langpair" value="en|zh-CN"-->
<!--			title="&#20013;&#25991;&#65288;&#31616;&#20307;&#65289;/Chinese Simplified"-->
<!--			src="http://photos1.blogger.com/img/43/1633/320/14324441_5ca5ce3423.jpg"-->
<!--			onclick="this.form.langpair.value=this.value" height="20"-->
<!--			type="image" width="30"></td>-->
<!--		</form>-->
<!--	</tr>-->
<!--</table>-->
