<div class="hastable">
<h1>View details</h1>
<table>
	<thead>
		<tr>			
			<td colspan="2">Customer info</td>
		</tr>
	</thead>
	<tbody style="overflow: scroll !important; height: 227px;">
		<tr>			
			<td width="150">Full name</td>
			<td><?php echo $this->Contact->full_name;?></td>
		</tr>
		<tr>			
			<td>Address</td>
			<td><?php echo $this->Contact->address;?></td>
		</tr>
		<tr>			
			<td>Email</td>
			<td><?php echo $this->Contact->email;?></td>
		</tr>
		<tr>			
			<td>Phone number</td>
			<td><?php echo $this->Contact->phone;?></td>
		</tr>
		<tr>			
			<td>Order product</td>
			<td><?php echo $this->Contact->name_product;?></td>
		</tr>
		<tr>			
			<td>Order date</td>
			<td><?php echo $this->Contact->created_date;?></td>
		</tr>
	</tbody>			
</table>
<table>
	<thead>
		<tr>			
			<td>Request content</td>
		</tr>
	</thead>
	<tbody style="overflow: scroll !important; height: 227px;">
		<tr>			
			<td><?php echo $this->Contact->mesage;?></td>
		</tr>	
	</tbody>
</table>
<button type="button" onclick="javascript:history.back();">Back</button>
</div>