<div class="hastable">
<h1>Manage testimonials</h1>
<a href="<?php echo $this->url(array('controller'=>'testimonials','action'=>'create'))?>"><button type="button">Add new</button></a>
<?php echo $this->Pagination($this->Pager,$this->url().'?page={%page}')?>
<table cellpadding="0" cellspacing="0" width="100%" class="tbl_list">
		<thead>
			<th>Title</th>
			<th>Customer name</th>
			<th>Customer email</th>
			<th>Created date</th>
			<th>Status</th>
			<th>Edit</th>
			<th>Delete</th>
		</thead>
		<?php foreach($this->Content as $Content):?>
		<tr class="<?php ++$i; echo($i%2)?'first':'second'?>">
			<td><?php echo $Content->title?></td>
			<td><?php echo $Content->customer_name?></td>
			<td><?php echo $Content->customer_email?></td>
			<td><?php echo $Content->created_date?></td>			
			<td><?php echo ($Content->status?"Yes":"No")?></td>				
			<td align="center" width="40px;"><a href="<?php echo $this->url(array('controller'=>'testimonials','action'=>'edit','id'=>$Content->id))?>"><img src="<?php echo $this->baseUrl('images/image_edit.png');?>" width="24px;"/></a></td>
			<td align="center" width="40px;"><a href="<?php echo $this->url(array('controller'=>'testimonials','action'=>'delete','id'=>$Content->id))?>"><img src="<?php echo $this->baseUrl('images/Delete.png');?>" width="24px;"/></a></td>
		</tr>
		<?php endforeach;?>
</table>
</div>