<div class="block-controls">	
	<ul class="controls-tabs js-tabs same-height with-children-tip">
		<li class="current" title="Basic info"><a title="" href="#tabs-1"><img height="24" width="24" src="<?php echo $this->baseUrl('images/icons/web-app/24/Profile.png');?>"></a></li>
	</ul>	
</div>
<?php if($this->error):?>
<div class="block-content no-title dark-bg">
    <p class="mini-infos">          
          <?php foreach($this->error as $error){echo '- '.$error.'<br/>';}?>
    </p>
</div>    
<?php endif;?>
<h1>Create a news</h1>
<form action="" method="post" enctype="multipart/form-data" class="form">
<div id="tabs-1" class="hastable">
<table>
	<tr>
		<td width="130"><span style="color:#CC0000;">*</span>Title</td>
		<td><?php echo $this->formText('title',$_REQUEST['title'],array('size'=>60 ))?></td>
	</tr>
	<tr>
		<td width="130">Description</td>
		<td><?php echo $this->formTextarea('description',$_REQUEST['description'],array('rows'=>5))?></td>
	</tr>
	<tr>
		<td width="130"><span style="color:#CC0000;">*</span>Content</td>
		<td><?php echo $this->formTextarea('content',$_REQUEST['content'],array('rows'=>5,'class'=>'mceEditor'))?></td>
	</tr>
	<tr>
		<td width="130">Image</td>
		<td><?php echo $this->formFile('images',$_REQUEST['images'])?> </td>
	</tr>
	<tr>
		<td width="130">Category</td>
		<td><?php $group = Newgroup::getOption(); echo $this->formSelect('group_id',$_REQUEST['group_id'],null,$group)?> </td>
	</tr>
	<tr>
		<td width="130">Video</td>
		<td><?php $video = Video::getOption(array('--Select video--')); echo $this->formSelect('video_id',$_REQUEST['video_id']?$_REQUEST['video_id']:"",null,$video)?> </td>
	</tr>
	<tr>
		<td width="130">Status</td>
		<td><?php $status = array("1"=>"Yes","0"=>"No"); echo $this->formSelect('status',$_REQUEST['status'],null,$status)?> </td>
	</tr>	
</table>
</div>
<button type="submit">Save</button>
&nbsp;
<button type="button" onclick="javascript:history.back()">Cancel</button>
</form>
