<div id="middle">
				<div class="indent">				
<div class="columns1">
						<div class="padding">
							<img alt="" src="images/6-t3.gif" /><br />
							<p class="p1">
								<strong class="b_text">Lorem ipsum dolor sit aectetuer adipiscing elit. Praesent vestibulum molestie lacus.</strong><br />
								Montes, nascetur ridiculus muulla dui. Fusce feugiat malesuada odio. Morbi nunc odio, gravida at, cursus nec, luctus a, lorem. Maecenas tristique orci ac sem. Duis ultricies pharetra mnec accumsan malesuada orci. Donec sit amet eros.<br class="clear" />
							</p>
							<form id="contact" action="" method="post" enctype="multipart/form-data">
								<div class="column1">
									<div class="row">
										<label>Name<span class="require_field">*</span></label>
									</div>
									<div class="row">
										<input type="text" class="input" value=""/>
									</div>
									<div class="row">
										<label>E-mail<span class="require_field">*</span></label>
									</div>
									<div class="row">
										<input type="text" class="input" value="" />
									</div>
									<div class="row">
										<label>Phone<span class="require_field">*</span></label>
									</div>
									<div class="row">
										<input type="text" class="input" value="" />
									</div>																	
								</div>
								<div class="column2">
									<div class="row">
										<label>Message<span class="require_field">*</span></label>
									</div>
									<div class="">
										<textarea style="width: 490px; height: 118px;"></textarea><br />										
									</div>	
								</div>
								<div class="clear"></div>
								<div class="div">
									<img id="contact_reset" alt="Reset data" src="images/icons/clear.gif" style="cursor:pointer;"> &nbsp; <img id="contact_submit" alt="Send contact" src="images/icons/send.gif"  style="cursor:pointer;">
								</div>
							</form>
				</div>
		</div>
	</div>
</div>