<?php if($this->error):?>
    	<div class="block-content no-title dark-bg">
               <p class="mini-infos"><?php foreach($this->error as $error){echo '- '.$error.'<br/>';}?></p>
         </div>
<?php endif;?>
<div class="block-controls">	
	<ul class="controls-tabs js-tabs same-height with-children-tip">
		<li class="current" title="Basic info"><a title="" href="#tab-stats"><img height="24" width="24" src="<?php echo $this->baseUrl('images/icons/web-app/24/Profile.png');?>"></a></li>
	</ul>	
</div>
<div class="hastable">
<h1>Edit member</h1>
<form method="post" class="form">
<input type="hidden" name="id"	value="<?php echo $this->Member->id?>" />
<div id="tab-stats">
<table>
	<tr>
		<td>Email</td>
		<td><?php echo $this->formText('email',$this->Member->email)?></td>
	</tr>
	<tr>
		<td>Password</td>
		<td><?php echo $this->formPassword('password',$this->Member->password)?></td>
	</tr>
	<tr>
		<td>Confirm Password</td>
		<td><?php echo $this->formPassword('confirmpassword','')?></td>
	</tr>
	<tr>
		<td>Full name</td>
		<td><?php echo $this->formText('name',$this->Member->name)?></td>
	</tr>
	<tr>
		<td>Position</td>
		<td><?php echo $this->formText('dept',$this->Member->dept)?></td>
	</tr>
	<tr>
		<td>Address</td>
		<td><?php echo $this->formText('address',$this->Member->address)?></td>
	</tr>
	<tr>
		<td>Identification number</td>
		<td><?php echo $this->formText('passport_no',$this->Member->passport_no)?></td>
	</tr>
	<tr>
		<td>Date of issue</td>
		<td><?php echo $this->formText('passport_date',$this->Member->passport_date)?></td>
	</tr>
	<tr>
		<td>Place of issue</td>
		<td><?php echo $this->formText('passport_address',$this->Member->passport_address)?></td>
	</tr>
	<tr>
		<td>Mobile</td>
		<td><?php echo $this->formText('mobile',$this->Member->mobile)?></td>
	</tr>
	<tr>
		<td>Tel/Fax</td>
		<td><?php echo $this->formText('tel',$this->Member->tel)?></td>
	</tr>

	<tr>
		<td>Roles</td>
		<td><?php echo $this->formSelect('member_type',$this->Member->member_type,null,Groups::getOption(array('--Select roles--')))?></td>
	</tr>
	<tr>
		<td>Status</td>
		<td><?php echo $this->formSelect('status',$this->Member->status,'',array('Disable','Enable'))?></td>
	</tr>
	<tr>		
		<td colspan="2" align="left"><button type="submit">Update</button>&nbsp;<a href="<?php echo $this->url(array("controller"=>"member","action"=>"index","modeule"=>"admin"));?>"><button type="button">Cancel</button></a></td>
	</tr>
</table>
</div>
</form>
</div>