<ul class="controls-buttons">
<?php for($i=1;$i<=$this->TotalPage;$i++):?> 
  <li><a href="<?php echo $this->url(array("controller"=>"member","action"=>"history","id"=>$this->id,"page"=>$i));?>"><?php echo $i;?></a></li>
<?php endfor;?>	
</ul>
<form method="get">
Member: <?php echo $this->formSelect('id',$_POST['id'],array(),Members::getOption(array(),array('--Select--')))?>
<?php echo $this->formSubmit('Xem','Xem nhật ký','page')?>
</form>
<br></br>
<div class="hastable">
<center><?php echo $this->error?></center>
<?php if($this->Log):?>
<table>
	<thead>
		<tr>
			<td>Thời điểm</td>
			<td>Phân mục</td>
			<td>Hành động</td>
			<td>IP</td>
		</tr>
	</thead>
	<tbody>
	<?php foreach($this->Log as $log):?>
		<tr>
			<td><?php echo $log['time']?></td>
			<td><?php echo $log['section']?></td>
			<td><?php echo $log['action']?></td>
			<td><?php echo $log['ip']?></td>
		</tr>
	<?php endforeach;?>
	</tbody>
</table>
<?php else:?>
Please select member!
<?php endif;?>
</div>