	<!doctype html>
<!--[if lt IE 8 ]><html lang="en" class="no-js ie ie7"><![endif]-->
<!--[if IE 8 ]><html lang="en" class="no-js ie"><![endif]-->
<!--[if (gt IE 8)|!(IE)]><!--><html lang="en" class="no-js"><!--<![endif]-->
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	
	<title>Constellation Admin Skin</title>
	<meta name="description" content="">
	<meta name="author" content="">
	
	<!-- Global stylesheets -->
	<link href="<?php echo $this->baseUrl('css/reset.css')?>" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->baseUrl('css/common.css')?>" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->baseUrl('css/form.css')?>" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->baseUrl('css/standard.css')?>" rel="stylesheet" type="text/css">
	<link href="<?php echo $this->baseUrl('css/special-pages.css')?>" rel="stylesheet" type="text/css">
	
	<!-- Favicon -->
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->baseUrl('favicon.ico')?>">
	<link rel="icon" type="image/png" href="<?php echo $this->baseUrl('favicon-large.png')?>">
	
	<!-- Modernizr for support detection, all javascript libs are moved right above </body> for better performance -->
	<script src="<?php echo $this->baseUrl('js/libs/modernizr.custom.min.js')?>"></script>
	
</head>
<body class="special-page login-bg dark">

	<section id="message">
		<div class="block-border"><div class="block-content no-title dark-bg">
			<?php if($this->error){?>
			<p class="mini-infos"><?php echo $this->error;?></p>
			<?php }else{?>
			<p class="mini-infos">Please enter username and password to login!</p>
			<?php }?>
		</div></div>
	</section>
	
	<section id="login-block">
		<div class="block-border"><div class="block-content">
			<!--
			IE7 compatibility: if you want to remove the <h1>, 
			add style="zoom:1" to the above .block-content div
			-->			
			<div class="block-header">Please login</div>
			<form class="form with-margin" name="login-form" id="login-form" method="post" action="">
				<input type="hidden" name="a" id="a" value="send">
				<p class="inline-small-label">
					<label for="login"><span class="big">User name</span></label>
					<input type="text" name="username" id="username" class="full-width" value="">
				</p>
				<p class="inline-small-label">
					<label for="pass"><span class="big">Password</span></label>
					<input type="password" name="password" id="password" class="full-width" value="">
				</p>
				
				<button type="submit" class="float-right">Login</button>
				<p class="input-height">
					<input type="checkbox" name="keep-logged" id="keep-logged" value="1" class="mini-switch" checked="checked">
					<label for="keep-logged" class="inline">Keep me logged in</label>
				</p>
			</form>
			
			<form class="form" id="password-recovery" method="post" action="">
				<fieldset class="grey-bg no-margin collapse">
					<legend><a href="#">Lost password?</a></legend>
					<p class="input-with-button">
						<label for="recovery-mail">Enter your e-mail address</label>
						<input type="text" name="recovery-mail" id="recovery-mail" value="">
						<button type="button">Send</button>
					</p>
				</fieldset>
			</form>
		</div></div>
	</section>	
	<!-- Generic libs -->
	<script src="<?php echo $this->baseUrl('js/libs/jquery-1.6.3.min.js')?>"></script>
	<script src="<?php echo $this->baseUrl('js/old-browsers.js')?>"></script>		<!-- remove if you do not need older browsers detection -->
	
	<!-- Template libs -->
	<script src="<?php echo $this->baseUrl('js/common.js')?>"></script>
	<script src="<?php echo $this->baseUrl('js/standard.js')?>"></script>
	<!--[if lte IE 8]><script src="<?php echo $this->baseUrl('js/standard.ie.js')?>"></script><![endif]-->
	<script src="<?php echo $this->baseUrl('js/jquery.tip.js')?>"></script>
	<!-- example login script -->
</body>
</html>
