<div class="hastable">
<form method="post" class="form">
<table width="100%">
	<tr valign="top">
		<td>Group name: <input type="text" name="name" value="<?php echo $this->Group->name?>" /></td>
		</tr>
		<tr>
		<td class="hastable">			
			<?php foreach($this->Resources as $key=>$Resource):?>
			<ul class="collapsible-list with-bg">
					<li id="controller-<?php echo $key;?>" class="closed" onclick="return OpenController(this.id);">	
					<b class="toggle"></b>
					<span>Module - <?php echo $Resource->name;?></span>							
							<ul class="with-icon icon-group">
							<?php foreach ($Resource->role as $role):?>
							<li id="<?php echo $key;?>" onclick="return ChangeAction(this.id);">
<input type="checkbox" name="Role[<?php echo $key?>][<?php echo $role->code?>]" value="1" <?php if($this->Group->role[$key][$role->code]==1):?> checked="checked"<?php endif;?> id="role_<?php echo $key?>_<?php echo $role->code?>" /> 
								<label for="role_<?php echo $key?>_<?php echo $role->code?>"><?php echo $role->name?></label>
							</li>
							<?php endforeach;?>
							</ul>	
					</li>	
			</ul>					
            <?php endforeach;?>
			</td>
	</tr>
	<tr>
	<td>
	<button type="submit">Save</button>
	&nbsp;<button type="button" onclick="javascript:history.back();">Cancel</button>
	</td>
	</tr>
</table>
</div>
</form>
<script>
OpenController = function(id){	
	var obj = document.getElementById(id);	
	if(obj.className == "closed"){
		$("#"+id).removeClass("closed");
	}else{
		$("#"+id).addClass("closed");
	}
}
ChangeAction = function(id){
	$("#controller-"+id).addClass("closed");
}
</script>