<div class="block-controls">	
	<ul class="controls-tabs js-tabs same-height with-children-tip">
		<li class="current" title="Basic info"><a title="" href="#tabs-1"><img height="24" width="24" src="<?php echo $this->baseUrl('images/icons/web-app/24/Profile.png');?>"></a></li>
	</ul>	
</div>
<?php if($this->error):?>
<div class="block-content no-title dark-bg">
    <p class="mini-infos">          
          <?php foreach($this->error as $error){echo '- '.$error.'<br/>';}?>
    </p>
</div>    
<?php endif;?>
<h1>Edit a category</h1>
<form action="" method="post">
<div id="tabs-1" class="hastable">
<table>
	<tr>
		<td width="130"><span style="color:#CC0000;">*</span>Name</td>
		<td><?php echo $this->formText('name',$this->Newgroup->name,array('size'=>60 ))?></td>
	</tr>
	<tr>
		<td width="130">Setions</td>
		<td><?php $setions = Setions::getOption(); echo $this->formSelect('setions_id',$this->Newgroup->setions_id,null,$setions)?> </td>
	</tr>
	<tr>
		<td width="130">Status</td>
		<td><?php $status = array("1"=>"Yes","0"=>"No"); echo $this->formSelect('status',$this->Newgroup->status,null,$status)?> </td>
	</tr>		
</table>
</div>
<button type="submit">Save</button>
&nbsp;
<button type="button" onclick="javascript:history.back()">Cancel</button>
</form>
</div>
