<div class="hastable">
<h1>Management product</h1>
<div id="qlqg" style="padding-bottom: 10px;">
<a href="<?php echo $this->url(array('controller'=>'product','action'=>'create'))?>"><button>Add product</button></a>
<?php echo $this->Pagination($this->Pager,$this->url().'?page={%page}')?>
</div>
<table cellspacing="0" cellpadding="0" width="100%" class="tbl_list">
		<thead>
			<th>Product name</th>
			<th>Product price</th>
			<th>Manufacturer</th>
			<th>Product Group</th>
			<!--<th>Lượt xem</th>-->
			<th>Status</th>
			<th>Edit</th>
			<th>Delete</th>
		</thead>
		<?php foreach($this->Product as $Product):?>
		<tr class="<?php ++$i; echo($i%2)?'first':'second'?>">
			<td><?php echo $Product->product_name?></td>
			<td><?php echo number_format ( $Product->product_price, 0 , '.' , ',' );?>&nbsp;VND</td>				
			<td><?php echo $Product->manufacturer?></td>
			<td><?php $Group = ProductGroup::getById($Product->id_group_product); echo $Group->name;?></td>	
			<!--<td><?php echo $Product->view?></td>-->
			<td><?php echo ($Product->status?"Yes":"No")?></td>		
			<td align="center" width="40px;"><a href="<?php echo $this->url(array('controller'=>'product','action'=>'edit','id'=>$Product->id))?>"><img src="<?php echo $this->baseUrl('images/image_edit.png');?>" width="24px;"/></a></td>
			<td align="center" width="40px;"><a href="<?php echo $this->url(array('controller'=>'product','action'=>'delete','id'=>$Product->id))?>"><img src="<?php echo $this->baseUrl('images/Delete.png');?>" width="24px;"/></a></td>
		</tr>
		<?php endforeach;?>
</table>
